name: gh-pages CD
on:
  push:
    branches:
      - "master"

env:
  CI: false

jobs:
  build_package_deploy:
    runs-on: self-hosted

    steps:
      - name: patch node gyp on windows to support Visual Studio 2019
      shell: powershell
      run: |
        npm install --global node-gyp@latest
        npm prefix -g | % {npm config set node_gyp "$_\node_modules\node-gyp\bin\node-gyp.js"}

      - name: Checkout repo
        uses: actions/checkout@v2.3.1

      - name: Install and build
        run: |
          yarn cache clean
          yarn install
          yarn prebuild

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.5.9
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist
