name: gh-pages CD
on:
  push:
    branches:
      - "master"

env:
  CI: false

jobs:
  build_package_deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - name: build scss and cleanup old packages
        run: |
          rm -rf node_modules package-lock.json yarn.lock
          npm rebuild node-sass

      - name: Checkout repo
        uses: actions/checkout@v2.3.1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install and build
        run: |
          yarn cache clean
          yarn install
          yarn prebuild

      - name: Deploy
        run: |
          git config --global user.name $user_name
          git config --global user.email $user_email
          git remote set-url origin https://${github_token}@github.com/${repository}
          npm run deploy
        env:
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
          github_token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
          repository: ${{ github.repository }}
